name: Build Debian

on:
  push:
    branches: [ main ]
    paths:
      - 'builders/**'
      - 'common/**'
      - '.github/workflows/build-debian.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'builders/**'
      - 'common/**'
      - '.github/workflows/build-debian.yml'
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codename: [bookworm, bullseye, trixie]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils parted wget
    
    - name: Build Debian ${{ matrix.codename }} image
      run: |
        cd builders
        chmod +x debian.sh
        ./debian.sh ${{ matrix.codename }}
    
    - name: Upload Debian ${{ matrix.codename }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: debian-${{ matrix.codename }}-qa-image
        path: builders/${{ matrix.codename }}-generic-amd64-qa.qcow2
        retention-days: 30
