name: Build AlmaLinux

on:
  push:
    branches: [ main ]
    paths:
      - 'builders/**'
      - 'common/**'
      - '.github/workflows/build-alma.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'builders/**'
      - 'common/**'
      - '.github/workflows/build-alma.yml'
  workflow_dispatch:

jobs:
  build-alma:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8, 9]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils parted wget

    - name: Build AlmaLinux ${{ matrix.version }} image
      run: |
        cd builders
        chmod +x alma.sh
        ./alma.sh ${{ matrix.version }}

    - name: Upload AlmaLinux ${{ matrix.version }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: almalinux-${{ matrix.version }}-qa-image
        path: builders/AlmaLinux-${{ matrix.version }}-GenericCloud-latest-qa.x86_64.qcow2
        retention-days: 30
